### ISSUE TITLE
Deposit Clears In

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/sommelier#109]
![Screen Shot 2022-04-06 at 2 37 11 PM](https://user-images.githubusercontent.com/56059752/162075812-4e848bc5-f819-4df2-a8a4-309614548ed9.png)

**Comment by henrio123** [comment]
Will close this ticket. It is not necessary for a customer to see it anymore as we don’t have active/inactive logic in the final contract version which means customers will anyway start earning interest after the deposit.
