### ISSUE TITLE
UX/UI - Nav - Connect wallet component

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#275]
**Header**

Hover state on Sommelier logo should not change to red
Bottom border on scroll should be `primary/ dark` not `primary/base`
![Screenshot 2022-06-17 at 13 04 54](https://user-images.githubusercontent.com/26877917/174276934-dc4723dc-9b8d-4eed-85b1-e2b85ac960e1.png)

Connect wallet component is outdated, the [new component (forms/ wallet) is available here](https://www.figma.com/file/jGzU591pLAM3kMIVa4Sjvd/Components?node-id=49%3A4953)
![Screenshot 2022-06-17 at 13 05 31](https://user-images.githubusercontent.com/26877917/174277051-2f88db60-45fa-46b0-b2c1-0c8222319f9d.png)

**Footer**

Missing capitalization on social links (all links can use CSS text-transform: capitalize;
![Screenshot 2022-06-17 at 13 06 21](https://user-images.githubusercontent.com/26877917/174277279-0987d8ee-e9d2-4162-9dda-6fb810be77d2.png)

**Comment by xanderjl** [comment]
![Image](https://user-images.githubusercontent.com/25848639/178085658-d1d6e46b-ceaa-4222-83a1-3326302b89a2.png)

🤷
