### ISSUE TITLE
Withdraw max and Bonding max give a slight different number that max in reality

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#337]
<img width="554" alt="Screenshot 2022-07-12 at 16 10 08" src="https://user-images.githubusercontent.com/26877917/178497640-b8dc3595-3fc9-49c0-a14d-d4cde8788efa.png">

![photo_2022-07-12 16 11 30](https://user-images.githubusercontent.com/26877917/178497846-92168e76-8852-4d3e-ac2b-3103fa49387b.jpeg)

**Comment by codingki** [comment]
This closed by https://github.com/strangelove-ventures/sommelier/pull/448
