### ISSUE TITLE
Bond gas fee estimation

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#360]
Charlie´s comment:
i think it will only cost about 1/10th of what amount you see as the estimate

i believe this is due to the Gas Limit being hard coded to 1,000,000 instead of letting Metamask run an estimate

This is similar to how the Deposit function was using 1,000,000 gas during testing.
Deposit was changed so it is actually accurate now.

But Bond is still set to 1,000,000 even though the actual transaction will only use something like 125,000 units of gas.

![Screenshot 2022-07-20 at 13 55 23](https://user-images.githubusercontent.com/26877917/180012019-0bc0c410-0814-42f0-b543-a5be4c2c7c67.png)

**Comment by codingki** [comment]
@henrio123 I'll check all transactions and measure the gas fees

**Comment by codingki** [comment]
Unbond button doesn't have a loading state, which is this can cause multiple clicks on the same tranche

**Comment by codingki** [comment]
https://github.com/strangelove-ventures/sommelier/issues/435

**Comment by henrio123** [comment]
@codingki tested in Staging, all good, ready for production
