### ISSUE TITLE
TVM chart- default latest TVM number

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#386]
Suggestion from Gytis:

Suggest doing the mouse tracking for the chart only when a user actually hovers over the trendline. Otherwise, if a mouse is on the left, it just shows $. The chart should by default show the last TVM number.

![2022-07-22 16 16 46](https://user-images.githubusercontent.com/26877917/180447160-3c20e036-d878-477f-bc3a-5d4c772afcc8.jpg)

**Comment by xanderjl** [comment]
https://sommelier-r4ccvb4eq-sommelierfinance.vercel.app/
