### ISSUE TITLE
Expected APY and Net Value show real value with delay

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#390]
Current situation:
Expected APY and Net Value show real values with a small delay or after page refresh.
Example Expected APY first shows always only Base Cellar APY 1.5%.

Expected result:
Show real values always in real-time.

**Comment by henrio123** [comment]
Can use small loader until we get calculations from subgraph

**Comment by xanderjl** [comment]
Asked this in telegram, but pasting here for the record:

There's a mutable val `expectedApy` that is initialized as the hardcoded 1.5% and is then updated to be `exptectedApy + potentialStakinApy` from the aave staker context. I saw the behavior defined in the issue on Henri's machine when we had our call, but have been unable to reproduce it locally. `useAaveStaker` exposes a `loading` and an `error` boolean. Actually haven't been able to get either of those bools to return true in testing. 

All that's to say; How should we be handling this? I can set a loading spinner until `expectedApy` is no longer the `1.5` hardcoded value. But what should we do for error handling? I could use a `setTimeout` that checks if the `expectedApy` is no longer `1.5` after n seconds, but then I'm not sure how we should notify the user. Perhaps have a toast with copy that reads. "A timeout error has occurred, please refresh the page for most up-to-date data from the cellar"?
