### ISSUE TITLE
Cellar name bug

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#393]
**Current situation:**
Cellar name: "Sommelier Aave V2 Stablecoin Cellar LP Token"
![Screenshot 2022-07-25 at 22 02 34](https://user-images.githubusercontent.com/26877917/180855079-9f3da6db-8999-4f61-994f-019b6cd36c74.png)

**Expected result:**
Cellar name: "Sommelier Aave V2 Stablecoin Cellar

**Comment by xanderjl** [comment]
This is actually solved in an open PR that's ready to merge. @Okekejr brought a few elements 1:1 with the Figma specs! Should be merged to staging shortly
