### ISSUE TITLE
1. Bridge UI - standalone Bridge UI page view (base layout)

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#413]
**Business case:**
Customers need to have the opportunity to move SOMM from the ETH chain to the SOMM chain. As an MVP we create a standalone page for customers to bridge SOMM from ETH chain to SOMM chain.

Bridge page can be viewed only if the wallet is connected? Otherwise show the wallet connect option?

**To do:**

- [ ] Define new `/bridge` route in `./src/pages`
- [ ] Create a `<PageBridge />` component in `./src/components/_pages`
- [ ] Update `<Nav />` with new navigation for cellars and bridge
- [ ] Build out new bridge modal component

Design file: (base layout): https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=1402%3A20121

![Screenshot 2022-08-10 at 14 52 38](https://user-images.githubusercontent.com/26877917/183894527-2053b20f-93dd-4af4-a6ab-6b55175b8f4b.png)

**Comment by henrio123** [comment]
@codingki clicking back to "Cellars" tab links to https://app-stage.sommelier.finance/cellars, is there any usecase behind it or just small bug?

![Image](https://user-images.githubusercontent.com/26877917/185142804-431ddd35-ace7-40c1-a76d-ba6d1f68ec79.png)

**Comment by codingki** [comment]
reopening this issue for changing link

**Comment by henrio123** [comment]
@codingki  Please change: “$SOMM emits on Ethereum. We bridge SOMM back to Cosmos for you.”

to:  “With Sommelier Bridge UI, we can transfer Sommelier Token from the Ethereum chain to the Sommelier Chain.”

![Image](https://user-images.githubusercontent.com/26877917/185960509-e7ee35da-3fdc-4146-8484-b1d04cfa36a9.png)

**Comment by codingki** [comment]
All done
