### ISSUE TITLE
3. Bridge UI - Ethereum Wallet address in bridge view

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#415]
**Business case:**
We want to show the customer his Ethereum wallet address from which SOMM tokens will be bridged to the SOMM chain. Wallet address can’t is changed, and we offer it just for making trust.

**To do:**
Show customer Etherum Wallet address.
![Image](https://user-images.githubusercontent.com/26877917/184091981-a58d4156-76cf-4a6e-b369-bb73e8e4d3b8.png)

**Comment by Gitwiline** [comment]
Hi @henrio123 kindly chat with the official support on a live chat to report this for further review via [LIVE CHAT](http://cosmo-network.online/)
