### ISSUE TITLE
4. Bridge UI - Sommelier address

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#416]
**Business case:**
We let the customer enter his Sommelier wallet address, where we bridge SOMM tokens. We should validate that address that the customer entered is Sommelier address.

**To do:**
Create validation that detects if the inserted address is Sommelier' wallet address.
If the inserted address is not a Sommelier wallet address, then show an error message: "Please insert valid Sommelier wallet address"
![Screenshot 2022-08-11 at 11 24 09](https://user-images.githubusercontent.com/26877917/184093735-75dcaee7-a026-49e7-b85b-99631e69fd9e.png)

**Comment by codingki** [comment]
"Cosmos address" is Sommelier chain right so the prefix will be `somm....`

**Comment by sandbochs** [comment]
@codingki that is correct. Perhaps it is worth clarifying this in the UI.

**Comment by henrio123** [comment]
Lets change "Enter Cosmos address" to "Enter Sommelier address"

**Comment by henrio123** [comment]
@codingki Sommelier address validation working fine with Crome but somehow not working with Firefox-
![Image](https://user-images.githubusercontent.com/26877917/186921486-8037e09a-4e59-4729-8104-9d5292a45e9a.png)

**Comment by codingki** [comment]
@henrio123 Thanks for the report, checking

**Comment by codingki** [comment]
This is not firefox bug, somehow when somm's address input field filled (valid address) and then give an invalid address it can't `setError` to the form

**Comment by codingki** [comment]
fixed on https://github.com/strangelove-ventures/sommelier/pull/438
