### ISSUE TITLE
6. Bridge UI - "Read more" link

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#418]
**Business case:**
Clicking the link will direct the customer to the Notion page, where we describe how bridging works.

To **do:**
 https://www.notion.so/Bridge-UI-88307640a6ab4f649b6a0b3cb6cb4d34 lets link this one behind "Read more" button.

![Screenshot 2022-08-11 at 11 45 15](https://user-images.githubusercontent.com/26877917/184096807-aa5e2684-38a7-4a0f-baa0-43729505d24e.png)

**Comment by codingki** [comment]
Is the readmore link is https://app.mural.co/t/henri6552/m/henri6552/1660137976273/9be08bb8feb02a5c27291d705e18ccfc80be7f23

**Comment by henrio123** [comment]
@codingki made empty Notion page here https://www.notion.so/Bridge-UI-88307640a6ab4f649b6a0b3cb6cb4d34 lets link this one behind "Read more" button. I will fill content and link Mural flow chart there soon.
