### ISSUE TITLE
7. Bridge UI - Approval of SOMM Metamask interaction

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#419]
**Business case:**
After the customer clicks the "Bridge SOMM" button, it will have to trigger metamask interactions, which ask for approval for the SOMM token.

**To do:**
Create functionality that after clicking "Bridge SOMM" it opens metamask for asking approval for SOMM.

**Engineering**

Somm Address: `0xa670d7237398238de01267472c6f13e5b8010fd1`
Amount: max uint256

Use the `useHandleTransaction` hook to submit the TX
Show an in progress toast as the TX is pending and close when complete.

![Image](https://user-images.githubusercontent.com/26877917/184898242-963533d0-9ea2-426c-828b-6f6ad39f4fb2.png)

Link to Figma: https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=1402%3A20121

**Comment by codingki** [comment]
I need Contract address, Abi(json), and what function on the contract to interact with.

**Comment by sandbochs** [comment]
Use the existing ERC20 abi

**Comment by henrio123** [comment]
Green toast "place holder" text= "Approval in progress"
