### ISSUE TITLE
Is there a post bridging UI?

### ISSUE THREAD

**Issue by codingki** [strangelove-ventures/sommelier#427]
after "Bridge $SOMM" clicked and the transaction is made, is there will be a UI to be created?

**Comment by henrio123** [comment]
Currently, we plan to show "Bridge Initiated" popup with transaction details after the second transaction is confirmed in Metamask.
![Screenshot 2022-08-16 at 21 35 41](https://user-images.githubusercontent.com/26877917/184954172-92364c8d-8ccf-40bd-aa6c-cc31eb8d04f1.png)

I included it in this ticket https://github.com/strangelove-ventures/sommelier/issues/420, but it might be good to split it into separate one?
