### ISSUE TITLE
(Cellar) APY

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/sommelier#52]
Overview Page:
![Screen Shot 2022-04-06 at 12 22 17 PM](https://user-images.githubusercontent.com/56059752/162052673-e26a7622-1697-4446-af36-f9811aee38b1.png)

Cellar Page:
![Screen Shot 2022-04-06 at 12 18 35 PM](https://user-images.githubusercontent.com/56059752/162052757-bbf33fc5-4f7f-434c-8592-7204a91c7fa1.png)

## **Front End:**

- [x] Overview Page
- [x] Cellar Page

**Comment by henrio123** [comment]
Confirmed with Sun, change the hardcoded value to **1.5%**.

FYI@boojamya

**Comment by xanderjl** [comment]
> Confirmed with Sun, change the hardcoded value to **1.5%**.

Just to confirm, this is for APY, not  the management fee?
