### ISSUE TITLE
Buy/Sell modal pricing data

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#523]
**"Sell" modal**

Figma: https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=1968%3A91403&t=9PacbvlULzq2HkAI-0

By default, Trend, Momentum, Steady ETH and Steady BTC strategies will withdraw proportionally current active assets such as ETH, BTC, and USDC.

We want to show next parameters:
ETH Weight
BTC Weight
USDC Weigh
Estimated USD
![Image](https://user-images.githubusercontent.com/26877917/197857627-99d5dd5f-94cf-4713-8b3a-b0162052666a.png)

**"Buy" modal**
![Image](https://user-images.githubusercontent.com/26877917/197858067-8c34e16e-f4ca-4e8d-82fc-6a3a055c1054.png)
We want to show next parameters:
Tokens
Estimated USD

**Comment by henrio123** [comment]
@yoniafek lets sync on that

**Comment by henrio123** [comment]
![Image](https://user-images.githubusercontent.com/26877917/197597764-27d2d1d6-0562-4d67-a788-6e6a3d990d49.png)

**Comment by henrio123** [comment]
Need to be in synced with -

![Image](https://user-images.githubusercontent.com/26877917/197851412-68154b94-56cc-4710-876a-75d7f3da4433.png)

**Comment by codingki** [comment]
I need the contents of these tooltip 
![CleanShot 2022-11-05 at 06 51 13](https://user-images.githubusercontent.com/39829726/200090559-1310dafb-c509-4e0e-9821-5bfac963b235.png)
