### ISSUE TITLE
FAQ under Cellars page

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#526]
**Business case:**
We want to replace the "Education" section on the Cellars page (https://app.sommelier.finance/) with a FAQ section for a better user experience.

We want to use the same FAQ content as currently on the Marketing site.

**Todo:**
Replace the "Education" section on the Cellars page with FAQ section, using the design: https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=1631%3A44003

**Comment by joshuanatanielnm** [comment]
Hey @henrio123 , where I can find the data for FAQ section?

**Comment by joshuanatanielnm** [comment]
Sure @henrio123
