### ISSUE TITLE
Cellar Cap and Current Deposits

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/sommelier#59]
<img width="791" alt="Screen Shot 2022-04-12 at 2 06 31 PM" src="https://user-images.githubusercontent.com/56059752/163054698-3470febe-facc-4a75-baf4-15b91761ea7b.png">

**Comment by henrio123** [comment]
Cellar cap and Current Deposits need to reflect same numbers in "Cellars" page also.

In current version Current deposit shows same numbers but Cellar cap shows different -

![Image](https://user-images.githubusercontent.com/26877917/177965419-8a4ff2d3-38b6-42cf-835a-ebd55834b10c.png)

**Comment by henrio123** [comment]
Cellar cap and Current Deposits need to reflect same numbers in "Cellars" page also.

In current version Current deposit shows same numbers but Cellar cap shows different -

![Image](https://user-images.githubusercontent.com/26877917/177965419-8a4ff2d3-38b6-42cf-835a-ebd55834b10c.png)
