### ISSUE TITLE
New Strategies - Strategy details pages Steady BTC

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#640]
**LAUNCH DATE: 29.11.2022 +5pm UTC**

Use existing Design which is used for Trend and momentum Strategy details pages..

**Engineering:**
Should we move text components into Sanity? How much effort would it take?

**Link:** https://app.sommelier.finance/strategies/BreakoutBTC/manage

**Contracts:**

Steady BTC: [0x4986fD36b6b16f49b43282Ee2e24C5cF90ed166d](https://etherscan.io/address/0x4986fd36b6b16f49b43282ee2e24c5cf90ed166d)

**Staking contract:**
CellarStaking deployment: [CellarStaking | Address 0xD1d02c16874e0714Fd825213e0C13eaB6dD9c25f | Etherscan](https://etherscan.io/address/0xD1d02c16874e0714Fd825213e0C13eaB6dD9c25f)

**Liquidity mining:**
Add Bond; Unbond, Unstake, Claim reawrds buttons, designs/views and functionalities like it was with Aave Strategy.

**Content:**

**Deposit assets:**
BTC
ETH
USDC
AMPL
BUSD
DAI
FEI
FRAX
GUSD
USDP
RAI
SUSD
TUSD
USDT
**Strategy Type:** Crypto portfolio
**Protocols:** Uniswap V3
**Management fee:**  2% (1.5% for strategy provider + 0.5% for protocol)
**Performance split:** 10% (7.5% for strategy provider + 2.5% for protocol)
**Strategy assets** WBTC, USDC

**Goal:**
Catch trends early by predicting the significant movement of prices consistently and accurately. Capture the majority of BTC price breakouts, and limit losses through trailing stops. 

**Highlights:**
Risk first" approach - capital preservation is more important than capital growth.

Always defined risk for every position prevailing from trade inception until trade exit.

Each trade strategy comprises two independent trade orders: 1 "Workhorse" with a fixed target and stop + 1 "Racehorse" with a trailing stop.

**Description:**
"Patache has pursued a pragmatic approach to developing a trading strategy instead of a strict theoretical framework. A foundation of our pragmatic approach is a ""risk first"" paradigm – capital preservation is more important than capital growth. The strategy emphasizes principal protection and steady, consistent returns while pursuing occasional ""home runs."" [Read more]

The trade management technique of BTC Breakout strategy comprises two components: a workhorse and a racehorse. The point of the workhorse is to nullify risk and capture a small profit/cover transaction cost, and the point of the racehorse is to pursue a larger payoff opportunity. Check the ""How it works"" section for detailed strategy performance explanations. 

The Strategy is expected to capture most of any positive price breakouts and limit losses through its trailing stops. Due to the nature of the strategy, it is designed to be held over a medium to the long term (6 months to a year). In this time, the benefits of being in the strategy are expected to emerge."

**Backtesting:**
Beginning Cellar Value: 500,000
Period: Period Tested: May 2021 -September 2022. First Trade: 6/11/2021 Last Trade: 9/29/2022
No. of Trades: 58 
Winning Trades/Losing Trades: 34 wins/24 losses (58%/42%)
Best Month: 6.3%
Worst Month: -2.6%
Worst Loss (Single Trade): -7,523on 6/21/2022
Worst Drawdown (Peak to trough): 5.21%
Cumulative Profit: 38.1%
Annualized Mean Return: 23.4%
Annualized Std.Dev of Return: 10.4%
Annualized Sharpe Ratio: 226%

**FAQ's:**
Who decides how to rebalance assets in the cellar?
Trade management and portfolio management rules are built into the algorithm smart contract. Please refer to the cellar description for details.

What is the portfolio composition?
Portfolio composition is USDC + underlying strategy asset
 
How often is the portfolio rebalanced?
We expect 5-7 trades a month
 
Does the cellar help to cut my losses?
All trades come with a defined risk and capital allocation. Please refer to the cellar description for details.
 
Does the strategy work in all market conditions?
The algorithm is direction neutral i.e., it will generate Long and Short signals. However due to limitations in trade execution, only long signals will be supported by the cellar. Eventually both long and short trades will be supported by the cellar.
 
When should the strategy be used?
Strategies are best suited to investors who fully understand their risk appetite. The algorithm does not have any “timing” bias.

**Strategy provider:** Patache
**Strategy provider logo:**  ![Image](https://user-images.githubusercontent.com/26877917/202199363-424bbf3f-c634-4d5c-8902-8a1ba18e0338.png)
**Strategy provider webpage:** https://www.algoreturns.com/patache/

**Comment by henrio123** [comment]
@joshuanatanielnm few changes

1. 1W Change vs ETH BTC 50 50 to    **1W Change vs USDC**
2. Remove Current deposits and Cellar Cap
3. Add Strategy performance chart
4. Change Strategy assets to **WBTC** and **USDC**
5. Remove some text from Backtesting tab
6. Remove Cellar performance chart


![Image](https://user-images.githubusercontent.com/26877917/203095120-b6b3658d-80c1-4255-b107-25fc72006105.png)

![Image](https://user-images.githubusercontent.com/26877917/203095169-01a415a2-0c23-4ecf-a6c8-e7e748d43116.png)

**Comment by henrio123** [comment]
Logos https://drive.google.com/drive/folders/11xJFOSMduZKwnx6MdgME14VTe336XBFg

**Comment by henrio123** [comment]
Bonding period and rewards: Shares receive a 1.1x boost by locking for 10 days, a 1.2x boost for locking for 14 days, and a 1.25x boost for locking for 20 days.   @codingki  please change these in Bond modal

**Comment by codingki** [comment]
what's eth btc mom/trend would look like @henrio123 ?
