### ISSUE TITLE
Patache Logo into "Strategy provider section"

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#657]
**Add a new Strategy provider Patache into "Strategy provider section"**

Add to:
Martketing site( https://www.sommelier.finance/)
All Strategy landing pages

Link: https://www.algoreturns.com/patache/

Logo 1:
![Image](https://user-images.githubusercontent.com/26877917/203544519-4ec8acfd-3fa9-47f0-9db5-939709afe0f0.png)

Logo 2:

![Image](https://user-images.githubusercontent.com/26877917/203544624-9b6b0f01-b4ec-46b8-846c-aede1626f2ac.png)

**Comment by yoniafek** [comment]
![Image](https://user-images.githubusercontent.com/37255810/203608472-318530c9-efeb-4153-879b-4c8fca5b82c2.png)



![Image](https://user-images.githubusercontent.com/37255810/203608524-65893d23-4a9b-405b-b010-516f810ff86f.png)
![Image](https://user-images.githubusercontent.com/37255810/203608523-1667ab9c-ebac-43a7-aed5-fa5c1da0747a.svg)
![Image](https://user-images.githubusercontent.com/37255810/203608525-16d20b18-7f65-4afe-8be6-f7699d57a912.png)


Included logos for marketing site and cellar

**Comment by yoniafek** [comment]
alternative AR logo

![Image](https://user-images.githubusercontent.com/37255810/203624553-4abfd42f-64c9-4b98-9d65-7f437c00531b.png)
![Image](https://user-images.githubusercontent.com/37255810/203624552-e88be067-9eb5-4080-9835-8f2e5bcec837.svg)



![Image](https://user-images.githubusercontent.com/37255810/203624616-0b8808d1-4a42-47a0-bec7-fab714ee38fb.png)
