### ISSUE TITLE
(Users) Net Value 

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/sommelier#68]
![Screen Shot 2022-04-06 at 12 18 35 PM](https://user-images.githubusercontent.com/56059752/162052041-f7aac1b5-0fe8-4058-ab27-a7ec1e274802.png)

**Comment by henrio123** [comment]
Just to note this same number needs to reflect on the "Cellars" page also-

![Image](https://user-images.githubusercontent.com/26877917/177964510-42f8e4ec-6e9b-4fca-bd1e-dadfdf0f71d0.png)
