### ISSUE TITLE
Aave Strategy APY

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#691]
Since the contract is not giving us the data we need, I think the easiest solution is to display the AAVE supply apy of the current token we are lending.

+ add back Rewards APY with previous tooltip text.

**Comment by sandbochs** [comment]
Instructions to calculate this 'APY'
- Fetch the share value from cellar day data for the last 10 days
- Find the most recent date where the share value changes compared to the day before (currently about once a week, will be once a day in future)
- Calculate the yield `(new price - prev price) / prev price`
- APY = yield * 52 * 100
