### ISSUE TITLE
Your current SOMM rewards- need to reflect the reward amount in the Cellar view

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/sommelier#70]
![Screen Shot 2022-04-06 at 12 18 35 PM](https://user-images.githubusercontent.com/56059752/162080871-f6e331f9-53b3-44b3-b5a3-237365148c84.png)

**Comment by henrio123** [comment]
@luckyOdisetti  "Cellars" page Rewards number does not reflect correct number right now - 

![Image](https://user-images.githubusercontent.com/26877917/177965034-29442d8a-186c-40f8-bc0f-96583b3a4719.png)

**Comment by henrio123** [comment]
Joe tested with the final Staking contract and confirmed the calculation is correct.

But still, need to reflect the reward amount in the Cellar view.

**Comment by henrio123** [comment]
closing this issue as Done
