### ISSUE TITLE
"Service unavailable" warning, remove current solution and add warning/restriction to Deposit/Buy modal

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#757]
Service unavailable needs to be removed.
Add Access restriction after the customer wants to Deposit.

+ use similar text like https://app.1inch.io/

Design:
https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=3230%3A155887&t=cuRs7plGOfLivf9U-1
(see page 📦 Geo-access update - Dec 8, 22)

**Comment by yoniafek** [comment]
Updated with figma link
