### ISSUE TITLE
Buy modal - Add “Injective”

### ISSUE THREAD

**Issue by henrio123** [strangelove-ventures/sommelier#758]
Move Somm to the Top
Add “Injective” +  Logo Transparent
Links: MVP Injective landing page, on Monday, will get pool links

Logo: https://drive.google.com/drive/u/2/folders/1jhbHPy2l7-VGEYxGW-Ec4DXFm35wM2IJ (symbols folder, transparent logo)

Requirements:
Track "Clicking injective"

**Comment by codingki** [comment]
order: somm, uniswap, injective
